deploy:
  branch:
    server: docs.zen.ci
    username: zenci
    dir: '{home}/github/{repo_owner}/{repo_name}/{branch}'
    env_vars:
      docroot: '{home}/domains/docs2.zen.ci'
      domain: 'docs2.zen.ci'
      database_name: zenci_docs
      database_user: zenci_docs
      database_pass_file: '{home}/docs.pass'
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: REPLACE
      b: "php {home}/github/Gormartsen/b/b.php"
      site_mail: noreply@zen.ci
      site_name: "Documentation for ZenCI"
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
      after: '{deploy_dir}/scripts/deploy_update.sh'
